version: "3.8"
services:
  mongodb:
    image: "mongo"
    container_name: twitter_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: .
    container_name: twitter_backend
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: "mongodb://twitter_mongodb:27017"

volumes:
  mongodb_data: